package me.matsumo.fanbox.core.logs.category

import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

// This class is automatically generated by generate-log-classes.
sealed class BillingLog : LogCategory {

    class Purchase internal constructor(
        private val referrer: String,
        private val isSuccess: Boolean,
    ) : BillingLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "billing")
            put("event_name", "purchase")
            put("referrer", referrer)
            put("is_success", isSuccess)
        }
    }

    class Consume internal constructor(
        private val isSuccess: Boolean,
    ) : BillingLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "billing")
            put("event_name", "consume")
            put("is_success", isSuccess)
        }
    }

    class Verify internal constructor(
        private val isSuccess: Boolean,
    ) : BillingLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "billing")
            put("event_name", "verify")
            put("is_success", isSuccess)
        }
    }

    /** 解約予約ユーザー向けリテンション UI の表示ログ。 */
    class RetentionPromptShown internal constructor(
        private val planType: String,
        private val unsubscribeDetectedAtMillis: Long?,
        private val isAnnualOfferShown: Boolean,
    ) : BillingLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "billing")
            put("event_name", "retention_prompt_shown")
            put("plan_type", planType)
            put("unsubscribe_detected_at_millis", unsubscribeDetectedAtMillis)
            put("is_annual_offer_shown", isAnnualOfferShown)
        }
    }

    /** 解約予約ユーザー向けリテンション UI の年額 CTA タップログ。 */
    class RetentionPromptAnnualClicked internal constructor() : BillingLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "billing")
            put("event_name", "retention_prompt_annual_clicked")
        }
    }

    /** 解約予約ユーザー向けリテンション UI の購読管理 CTA タップログ。 */
    class RetentionPromptManageClicked internal constructor(
        private val platform: String,
    ) : BillingLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "billing")
            put("event_name", "retention_prompt_manage_clicked")
            put("platform", platform)
        }
    }

    /** 解約予約ユーザー向けリテンション UI の dismiss 操作ログ。 */
    class RetentionPromptDismissed internal constructor(
        private val reason: String,
    ) : BillingLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "billing")
            put("event_name", "retention_prompt_dismissed")
            put("reason", reason)
        }
    }

    companion object {
        // 購入リクエスト
        fun purchase(
            referrer: String,
            isSuccess: Boolean,
        ) = Purchase(referrer, isSuccess)

        // 消費リクエスト
        fun consume(
            isSuccess: Boolean,
        ) = Consume(isSuccess)

        // 検証リクエスト
        fun verify(
            isSuccess: Boolean,
        ) = Verify(isSuccess)

        // リテンション UI 表示
        fun retentionPromptShown(
            planType: String,
            unsubscribeDetectedAtMillis: Long?,
            isAnnualOfferShown: Boolean,
        ) = RetentionPromptShown(planType, unsubscribeDetectedAtMillis, isAnnualOfferShown)

        // リテンション UI 年額 CTA
        fun retentionPromptAnnualClicked() = RetentionPromptAnnualClicked()

        // リテンション UI 購読管理 CTA
        fun retentionPromptManageClicked(
            platform: String,
        ) = RetentionPromptManageClicked(platform)

        // リテンション UI dismiss
        fun retentionPromptDismissed(
            reason: String,
        ) = RetentionPromptDismissed(reason)
    }
}
