package me.matsumo.fanbox.core.logs.category

import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

// This class is automatically generated by generate-log-classes.
sealed class PostsLog : LogCategory {

    class Download internal constructor(
        private val type: String,
        private val postId: String,
        private val itemId: String,
        private val extension: String,
        private val isSuccess: Boolean
    ) : PostsLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "posts")
            put("event_name", "download")
            put("type", type)
            put("post_id", postId)
            put("item_id", itemId)
            put("extension", extension)
            put("is_success", isSuccess)
        }
    }

    companion object {
        // 投稿をダウンロードした際のログ
        fun download(
            type: String,
            postId: String,
            itemId: String,
            extension: String,
            isSuccess: Boolean
        ) = Download(type, postId, itemId, extension, isSuccess)
    }
}
