package me.matsumo.fanbox.core.logs.category

import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

// This class is automatically generated by generate-log-classes.
sealed class ReviewsLog : LogCategory {

    class RequestReview internal constructor() : ReviewsLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "reviews")
            put("event_name", "request_review")
        }
    }

    class TryRequestReview internal constructor() : ReviewsLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "reviews")
            put("event_name", "try_request_review")
        }
    }

    class Reviewed internal constructor() : ReviewsLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "reviews")
            put("event_name", "reviewed")
        }
    }

    companion object {
        // レビューをリクエストした際のログ
        fun requestReview() = RequestReview()

        // レビューをリクエストする処理を試みた際のログ
        fun tryRequestReview() = TryRequestReview()

        // レビューが完了した際のログ
        fun reviewed() = Reviewed()
    }
}
