name: Translations

on:
  release:
    types: [ released, prereleased ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  translations:
    name: Translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: translate
        run: |
          java -jar ./scripts/kmp-translation.jar \
            --target-languages="ko,zh-rCN,ru" \
            --base-dir="./core/resources/src/commonMain/composeResources" \
            --timeout=5 \
            --api-key=${{ secrets.OPENAI_API_KEY }} \
            --model="o3-mini"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: update translations
          title: Update Translations
          delete-branch: true
          reviewers: matsumo0922
